service: lambda-serverless-cyates

provider:
  name: aws
  runtime: nodejs6.10
  stage: demo
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "apigateway:GET"
      Resource:
        - "arn:aws:apigateway:${self:provider.region}::/restapis*"

plugins:
  - serverless-plugin-typescript

package:
  include:
    src/**/!(*.spec).js
  exclude:
    - node_modules/**/*

custom:
  documentation: ${file(./swagger/documentation.yml)}
  customDomain:
    basePath: "api"
    domainName: serverless-sample.balassy.me
    certificateName: serverless-sample.balassy.me
    stage: ${self:provider.stage}
    createRoute53Record: true
  output:
    file: .serverless/output.json
